name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy backend
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/backend
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
