name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH and deploy backend
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
          docker stop mada-backend || true
          docker rm mada-backend || true
          docker pull saehe/mada-backend:latest
          docker run -d --name mada-backend -p 8080:8080 saehe/mada-backend:latest
        EOF
