name: Backend CI/CD

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: saehe/mada-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Fail early if secrets missing
        shell: bash
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          if [ -z "${SERVER_HOST}" ]; then echo "::error::Missing SERVER_HOST secret"; exit 1; fi
          if [ -z "${SERVER_SSH_KEY}" ]; then echo "::error::Missing SERVER_SSH_KEY secret"; exit 1; fi

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}              # <— 이게 비어있으면 방금 그 에러
          username: ${{ secrets.SERVER_SSH_USER || 'ubuntu' }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /home/ubuntu/app
            docker-compose pull backend
            docker-compose up -d backend
            docker image prune -f || true
            curl -fsS -o /dev/null http://127.0.0.1:8080/api/users/health || true

