# .github/workflows/backend-cicd.yml
name: Backend CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

env:
  # Docker Hub 이미지 (예: dockerhub_username/repo)
  IMAGE_NAME: saehe/mada-backend
  # docker-compose 서비스 이름들 (backend만 갱신하고 싶으면 'backend'만 남기세요)
  SERVICES: "backend express"
  # EC2 내 앱 디렉터리 (compose가 있는 곳)
  REMOTE_APP_DIR: /home/ubuntu/app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (Spring backend image)
        uses: docker/build-push-action@v5
        with:
          context: .              # 리포 구조에 맞게 필요 시 './backend' 등으로 변경
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Validate required secrets
        shell: bash
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_SSH_USER: ${{ secrets.SERVER_SSH_USER }}
        run: |
          [[ -n "$SERVER_HOST" ]] || { echo "::error::Missing SERVER_HOST secret"; exit 1; }
          [[ -n "$SERVER_SSH_KEY" ]] || { echo "::error::Missing SERVER_SSH_KEY secret"; exit 1; }
          : "${SERVER_SSH_USER:=ubuntu}"
          echo "Using ${SERVER_SSH_USER}@${SERVER_HOST}"

      # ✅ compose 최신본을 EC2로 복사 (경로를 리포 구조에 맞게 변경)
      - name: Upload docker-compose to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER || 'ubuntu' }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"          # ← 리포에 있는 실제 경로/파일명으로 수정 가능 (예: 'app/docker-compose.yml')
          target: "/home/ubuntu/app/"           # ← 서버 compose가 있는 디렉터리

      - name: Deploy to EC2 via SSH (docker-compose)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USER || 'ubuntu' }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -euo pipefail

            cd ${{ env.REMOTE_APP_DIR }}

            # docker compose / docker-compose 호환
            if command -v docker compose >/dev/null 2>&1; then
              DC="docker compose"
            else
              DC="docker-compose"
            fi

            echo "[CI/CD] Pull latest images: ${{ env.SERVICES }}"
            $DC pull ${{ env.SERVICES }}

            echo "[CI/CD] Recreate services (no deps)"
            $DC up -d --no-deps --force-recreate ${{ env.SERVICES }}

            echo "[CI/CD] Prune dangling images"
            docker image prune -f || true

            echo "[CI/CD] Health check (backend)"
            set +e
            curl -fsS -m 8 http://127.0.0.1:8080/actuator/health || \
            curl -fsS -m 8 http://127.0.0.1:8080/api/users/health || true
            set -e

            echo "[CI/CD] Done."
